Modify the problem that the group name cannot be obtained
uwolfer/gerrit-rest-java-client pull request #114
Opened 2020-09-07 12:57 UTC by luxiaowan

In use, I found that the name of the group could not be obtained. After checking the source code, I found that in the class Groups#ListRequest, id was used to assign a value to name

2020-09-07 18:07 UTC, uwolfer commented
Can you please post some details about the bug? Does it lead in an exception? Or does it just not work as expected?

2020-09-10 06:39 UTC, luxiaowan commented
> Can you please post some details about the bug? Does it lead in an exception? Or does it just not work as expected?

Hi, it's a great honor to receive your reply. It is not a bug, just dose not work as expected. When I get the list of group, id and name are thr same value, like that:
![dee1b4d89b90ba5a6bbee9de42ae829](https://user-images.githubusercontent.com/20291973/92688322-bf9edb80-f36f-11ea-83cd-0330338a598c.png)

The key of map is my group's name, but the instance's name is null.It not work as expected, and I don't think it is reasonable. So I modify it, and I would like to bring your attention to review it. the result is:
![7ff88bf5036c07605f7cab8b19f882d](https://user-images.githubusercontent.com/20291973/92689208-34264a00-f371-11ea-99e9-1cdc42462bf0.png)

Thank you.

2020-09-22 20:35 UTC, uwolfer requested changes

2020-09-22 20:35 UTC, uwolfer commented on src/main/java/com/google/gerrit/extensions/api/groups/Groups.java
> +      List<GroupInfo> result = new ArrayList<>(map.values());
Files in the com.google package should not be touched as these are copied over from official Gerrit source from time to time. Does your "fix" also work without this change? Or do you see any alternatives to fix this issue?

2026-08-22 11:12 UTC, closed without merging